spring.application.name=demo


spring.ai.google.genai.api-key=AQ.Ab8RN6JkRVEeQv9BtKyWFcX4KFEdjqYHONvAtbFkx43cdx80wg
spring.ai.google.genai.chat.options.model=gemini-3.6-flash
management.endpoints.web.exposure.include=*
